--
-- 0016 — buying more makes it cheaper.
--
-- `products.price` is one number, which is right for anything sold one at a
-- time and wrong for anything sold by the roll, the ream or the box. A shop
-- whose price list reads
--
--     1/2"   1-4 rolls ₱500    5-9 rolls ₱450    10+ rolls ₱400
--
-- cannot say that at all today. It has three choices, and all three are bad:
-- publish the dearest price and discount by hand on every order, publish the
-- cheapest and lose money on small ones, or create three products that are
-- the same thing and hope nobody buys four of one and six of another.
--
-- So a product may carry a ladder. No rows means the old behaviour exactly —
-- one price, whatever the quantity — so nothing that exists today changes.
--

CREATE TABLE IF NOT EXISTS public.product_price_breaks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id text NOT NULL
    REFERENCES public.products(id) ON DELETE CASCADE,
  -- Buy this many and every one of them costs `unit_price`. The ladder is
  -- "all units", not marginal: at ten rolls all ten are ₱400, which is how
  -- the shop's own price list reads and how a customer expects it to work.
  min_qty numeric NOT NULL,
  unit_price numeric NOT NULL,
  CONSTRAINT product_price_breaks_min_qty_check CHECK (min_qty > 0),
  CONSTRAINT product_price_breaks_unit_price_check CHECK (unit_price >= 0),
  -- One price per threshold. Two rows saying "from 5" is a question with two
  -- answers, and whichever the query happened to return would be the price.
  CONSTRAINT product_price_breaks_unique UNIQUE (product_id, min_qty)
);

CREATE INDEX IF NOT EXISTS product_price_breaks_product_idx
  ON public.product_price_breaks (product_id, min_qty);

ALTER TABLE public.product_price_breaks ENABLE ROW LEVEL SECURITY;

-- Readable by anyone: it is a price list, and it is on the menu.
CREATE POLICY product_price_breaks_read ON public.product_price_breaks
  FOR SELECT USING (true);

-- Written by whoever sets prices. Same rule as the products themselves.
CREATE POLICY product_price_breaks_write ON public.product_price_breaks
  FOR ALL USING (public.is_manager()) WITH CHECK (public.is_manager());
