--
-- 0019 — the photograph the customer approves before anything is made.
--
-- The made-to-order steps have included `proof_sent` and `approved` since the
-- seed was written, and there has been no way to send a proof. The statuses
-- described a process the software could not carry out.
--
-- It matters more here than the name suggests. A customer has paid a deposit
-- on something that does not exist, and the proof is the moment they find out
-- whether it is what they meant. Doing that over Messenger works until it
-- doesn't: the approval is a message in a thread nobody can find in March,
-- and "you said yes to this" becomes an argument with no record.
--
-- So it is a row. Who sent what, when, what the customer said back, and which
-- attempt it was.
--

CREATE TABLE IF NOT EXISTS public.order_proofs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id text NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,

  -- Which attempt this is. A second proof does not replace the first: the
  -- first is what was rejected, and the note saying why is the reason the
  -- second looks as it does.
  version integer NOT NULL DEFAULT 1,

  image_url text NOT NULL,
  /** What the shop wants looked at. "Is the shade of maroon right?" */
  note text,

  sent_at timestamp with time zone DEFAULT now() NOT NULL,
  sent_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,

  --
  -- The customer's answer. Null until they give one.
  --
  -- 'approved' means make it. 'changes' means do not, and `reply` says what
  -- to change. There is no third answer, and silence is not one either — an
  -- unanswered proof is a job that has not started, which is what the order
  -- board should be showing.
  --
  decision text,
  reply text,
  decided_at timestamp with time zone,

  CONSTRAINT order_proofs_version_check CHECK (version > 0),
  CONSTRAINT order_proofs_decision_check
    CHECK (decision IS NULL OR decision = ANY (ARRAY['approved'::text, 'changes'::text])),
  -- A decision without a time, or a time without a decision, is half a record
  -- of the one fact this table exists to hold.
  CONSTRAINT order_proofs_decided_together
    CHECK ((decision IS NULL) = (decided_at IS NULL)),
  -- Asking for changes without saying what to change is not a reply.
  CONSTRAINT order_proofs_changes_need_a_reason
    CHECK (decision IS DISTINCT FROM 'changes' OR btrim(coalesce(reply, '')) <> ''),
  CONSTRAINT order_proofs_one_per_version UNIQUE (order_id, version)
);

CREATE INDEX IF NOT EXISTS order_proofs_order_idx
  ON public.order_proofs (order_id, version DESC);

-- Waiting on the customer, across every order at once. The one query the
-- order board asks that this table cannot already answer cheaply.
CREATE INDEX IF NOT EXISTS order_proofs_undecided_idx
  ON public.order_proofs (order_id)
  WHERE decision IS NULL;

ALTER TABLE public.order_proofs ENABLE ROW LEVEL SECURITY;

--
-- A customer sees the proofs on their own orders, and nobody else's.
--
-- Written against `orders.customer_id` rather than trusting an id passed in:
-- a proof is a photograph of something a person is paying for, and the whole
-- point of the row is that it is evidence.
--
CREATE POLICY order_proofs_read ON public.order_proofs
  FOR SELECT USING (
    public.is_staff()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_proofs.order_id AND o.customer_id = auth.uid()
    )
  );

-- Only the shop sends a proof.
CREATE POLICY order_proofs_insert ON public.order_proofs
  FOR INSERT WITH CHECK (public.is_staff());

--
-- Answering one is the customer's to do, and only once.
--
-- The `decision IS NULL` on the USING side is what makes it once: an
-- answered proof is no longer a row this policy can reach, so an approval
-- cannot be quietly turned into a rejection after the thing is made.
--
CREATE POLICY order_proofs_decide ON public.order_proofs
  FOR UPDATE USING (
    decision IS NULL
    AND EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_proofs.order_id AND o.customer_id = auth.uid()
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_proofs.order_id AND o.customer_id = auth.uid()
    )
  );

-- Staff may correct their own send — a wrong photograph, a typo in the note.
CREATE POLICY order_proofs_staff_update ON public.order_proofs
  FOR UPDATE USING (public.is_staff()) WITH CHECK (public.is_staff());

-- The customer's screen has to know the moment a proof lands, or they find
-- out by refreshing a page they have no reason to refresh.
ALTER TABLE public.order_proofs REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_proofs;
