--
-- 0020 — the questions that turn "a bouquet" into a thing that can be made.
--
-- 0013 added `order_lines.spec jsonb` and nothing has ever written to it. The
-- column was the easy half. The hard half is that a made-to-order shop cannot
-- start work from a line that says "3-stem bouquet ₱850" — somebody still has
-- to go back to the customer and ask which colours, whose name, spelled how,
-- and by then the deposit is a week old and the answer is in a Messenger
-- thread that the person actually cutting the ribbon cannot see.
--
-- So the questions are rows, and the answers are stored on the line.
--
-- Rows rather than columns, and rows rather than a list in the code, for the
-- same reason the order statuses are rows: a ribbon shop asks about stems and
-- printed names, a cake shop asks about flavour and the message on top, and
-- neither of them should need a developer to add a question. The shop learns
-- what to ask by doing the work — this is where that learning goes.
--

CREATE TABLE IF NOT EXISTS public.spec_questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- The stable name the answer is filed under, so renaming the question on
  -- screen does not orphan every answer already given to it. Constrained to a
  -- slug because it is a JSON key: a space or a quote in here is a key that
  -- some reader somewhere will get wrong.
  key text NOT NULL UNIQUE,

  -- What a person is actually asked.
  label text NOT NULL,
  -- The example that stops the wrong answer. "Exactly as it should be
  -- printed, including the middle initial."
  hint text,

  --
  -- What kind of answer it is. This decides the control on the screen and
  -- nothing else — every answer is stored and printed as text, because a
  -- number here ends up on a ribbon, and 12 and "12" are the same ribbon.
  --
  kind text NOT NULL DEFAULT 'text',
  -- For 'choice' only: the answers on offer. A fixed list is how a shop stops
  -- receiving "maroon", "Maroon", "dark red" and "burgundy" as four colours.
  options text[] DEFAULT '{}'::text[] NOT NULL,

  -- A question that must be answered before a quote can be saved. Use it
  -- sparingly: a required question the customer has not decided yet is a
  -- quote that cannot be written down.
  required boolean DEFAULT false NOT NULL,

  --
  -- Which work this is asked about. NULL means every job.
  --
  -- ON UPDATE CASCADE because a category's name IS its key here, and renaming
  -- "Graduation" should not silently unhook the questions about it. ON DELETE
  -- SET NULL rather than CASCADE: deleting a category should not delete the
  -- shop's questions, it should widen them.
  --
  category text REFERENCES public.catalog_categories(name)
    ON UPDATE CASCADE ON DELETE SET NULL,

  sort_order integer DEFAULT 0 NOT NULL,
  -- Retired rather than deleted. A question no longer asked is still the
  -- question that was asked on every order already taken.
  is_active boolean DEFAULT true NOT NULL,

  created_at timestamp with time zone DEFAULT now() NOT NULL,

  CONSTRAINT spec_questions_key_check CHECK (key ~ '^[a-z][a-z0-9_]*$'),
  CONSTRAINT spec_questions_label_check CHECK (btrim(label) <> ''),
  CONSTRAINT spec_questions_kind_check CHECK (
    kind = ANY (ARRAY['text'::text, 'long_text'::text, 'number'::text,
                      'choice'::text, 'date'::text, 'yes_no'::text])
  ),
  -- A dropdown with one option is a label, and one with none is a dead end
  -- the person filling the form cannot get past.
  CONSTRAINT spec_questions_choice_needs_options CHECK (
    kind <> 'choice' OR coalesce(array_length(options, 1), 0) >= 2
  )
);

-- The one query every screen makes: what do I ask about this job, in order.
CREATE INDEX IF NOT EXISTS spec_questions_active_idx
  ON public.spec_questions (sort_order, id)
  WHERE is_active;

ALTER TABLE public.spec_questions ENABLE ROW LEVEL SECURITY;

-- Readable by anyone, like the categories are. These are the questions a shop
-- would print on a paper order form; there is nothing in them to protect, and
-- public read is what lets an enquiry form on the shopfront ask them without
-- a migration first.
CREATE POLICY spec_questions_read ON public.spec_questions
  FOR SELECT USING (true);

-- Changing what the shop asks is the owner's, like prices and categories.
CREATE POLICY spec_questions_write ON public.spec_questions
  USING (public.is_owner()) WITH CHECK (public.is_owner());

--
-- The answers themselves live on the line, in the column 0013 made.
--
-- Shaped `{"answers":[{"key":…,"label":…,"value":…}]}` — the label copied in
-- beside the key on purpose. It is the difference between an order from March
-- that still reads "Name on the ribbon: Krizzia" and one that reads
-- "name_on_ribbon: Krizzia" because the question was reworded in April.
--
COMMENT ON COLUMN public.order_lines.spec IS
  'The answers that make this line the thing it is. {"answers":[{key,label,value}]} — the label snapshotted so an order stays readable after the question is reworded.';
